# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: openjverein build check

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
    paths:
      - 'plugin.xml'
      - 'build/**'
      - 'lib/**'
      - 'lib.src/**'
      - 'src/**'
jobs:
  build:
    name: Try to compile the current pull request

    runs-on: ubuntu-latest

    steps:
    - name: Checkout and Build (Reusable)
      uses: ./.github/workflows/reusable-build.yml

    - name: Checkout openjverein
      id: openjverein_checkout
      uses: actions/checkout@v4
      with:
        path: jverein

    - name: Build openjverein plugin
      id: buildtest
      working-directory: ./
      run: ant -noinput -buildfile jverein/build/build.xml compile
