name: Fork Sync

on:
  schedule:
    - cron: '21 */2 * * *'
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork-sync branch
        uses: actions/checkout@v4
        with:
          ref: fork-sync
          fetch-depth: 0

      - name: Set up git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream
        run: |
          git remote add upstream https://github.com/openjverein/jverein.git
          git fetch upstream --prune

      - name: Reset master to upstream/master
        run: |
          git checkout --track origin/master || git checkout master
          git reset --hard upstream/master
          git push origin master --force

      - name: Reset 4.0 to upstream/4.0
        run: |
          if git ls-remote --exit-code upstream 4.0; then
            git checkout --track origin/4.0 || git checkout 4.0 || git checkout -b 4.0
            git reset --hard upstream/4.0
            git push origin 4.0 --force
          fi

      - name: Reset 3.2 to upstream/3.2
        run: |
          if git ls-remote --exit-code upstream 3.2; then
            git checkout --track origin/3.2 || git checkout 3.2 || git checkout -b 3.2
            git reset --hard upstream/3.2
            git push origin 3.2 --force
          fi
