name: Merge master branch bugfixes into feature branches

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - plugin.xml
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge master -> feature-3.1.0
        uses: mtanzi/action-automerge@v1
        id: merge-master-feature-310
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source: 'master'
          target: 'feature-3.1.0'
          webhook_url: #if present add the Slack webhook
