name: Merge master branch bugfixes into feature branches

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - plugin.xml
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout openjverein
        uses: actions/checkout@v4

      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"

      - name: Merge master into feature-3.1.0
        run: |
            git fetch --unshallow
            git checkout feature-3.1.0
            git pull
            git merge master --no-ff --no-commit
            git merge --abort
            git status
            git merge -s ours master -m "Auto-merge master into feature-3.1.0"
            git push
