name: Merge master branch bugfixes into feature branches

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - plugin.xml
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout openjverein
        uses: actions/checkout@v4

      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
          git fetch --unshallow

      - name: Check for merge conflicts for master into feature-3.1.0
        run: |
          git checkout feature-3.1.0
          git pull
          git merge master --no-ff --no-commit
          git merge --abort
          git reset --hard HEAD
          git status

      - name: Merge master into feature-3.1.0
        if: always()
        run: |
          git checkout feature-3.1.0
          git pull
          git merge -X ours master -m "Auto-merge master into feature-3.1.0" --stat
          git push origin
